### ISSUE TITLE
change python to python3

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs-platform-afu-bbb#21]
in Redhat RHEL 8.8, python command is removed.

https://github.com/OFS/ofs-platform-afu-bbb/blob/511b25b71e3f731b09be1b40c98302f4a0c4a2fc/plat_if_develop/ofs_plat_if/scripts/gen_ofs_plat_if#L1

kindly replace 

```
#!/usr/bin/env python 
```
with
```
#!/usr/bin/env python3 
 ```
 
 in python scripts

**Comment by michael-adler** [comment]
That makes sense, unfortunately. Our RH 9 machines have a link from python to python3, but I accept that the ambiguity is a problem.

**Comment by michael-adler** [comment]
Code updated
