### ISSUE TITLE
example AFU host_chan_params get stuck in test_avalon7_burst3.txt (latency mode)

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/ofs-platform-afu-bbb#23]
i followed the AFU developement guide
https://ofs.github.io/ofs-2024.1-1/hw/common/user_guides/afu_dev/ug_dev_afu_ofs_agx7_pcie_attach/ug_dev_afu_ofs_agx7_pcie_attach/#3-compiling-an-afu

to build the `host_chan_params` AFU.

```
cd ofs-platform-afu-bbb/plat_if_tests/host_chan_params
afu_synth_setup -s hw/rtl/test_avalon7_burst3.txt afu_dev
cd afu_dev
$OPAE_PLATFORM_ROOT/bin/afu_synth
```

my afu.qsf has following defines
```
set_global_assignment -name VERILOG_MACRO "TEST_PARAM_BURST_CNT_WIDTH=3"
set_global_assignment -name VERILOG_MACRO "TEST_PARAM_IFC_AVALON"
```

The AFU is successfully build without any timing errors. so i build and run software application
```
./host_chan_params
```
[log2.txt](https://github.com/OFS/ofs-platform-afu-bbb/files/15091969/log2.txt)

it passed

but i tried with latency argument, it get stuck

```
./host_chan_params --latency
```

```
# Engine mask: 1
# Burst size: 7
# Mode: read+write
Read GB/s, Write GB/s, Read Inflight Lines Limit, Read Max Measured Inflight Lines, FIM Read Max Measured Inflight Lines, Write Inflight Lines Limit, Read Avg Latency ns, FIM Read Avg Latency ns, Write Avg Latency ns
0.75 3.82 7 13 13 7 604 557 106
1.41 7.64 8 14 14 8 619 568 106
1.44 7.64 12 18 18 12 619 570 106
2.12 11.47 16 22 22 16 621 568 106
2.20 11.47 20 26 26 20 613 562 106
2.83 15.28 24 30 30 24 623 568 106
2.74 15.28 28 34 34 28 662 609 106
3.52 19.10 32 38 38 32 630 574 106
4.11 22.92 36 42 42 36 638 585 106
4.22 22.92 40 46 46 40 636 583 106
4.71 25.99 44 50 50 44 651 598 109
4.86 26.00 48 54 54 48 649 596 109
5.31 25.99 52 58 58 52 664 613 126
5.58 26.00 56 62 62 56 651 598 126
6.09 26.00 60 66 66 60 655 602 140
6.64 25.99 64 70 70 64 660 606 140
6.70 26.00 68 74 74 68 668 615 140
7.33 26.00 72 78 78 72 657 606 140
7.52 26.00 76 82 82 76 657 606 140
8.02 26.00 80 86 86 80 660 609 140
8.23 26.00 84 90 90 84 660 609 140
8.63 26.00 88 94 94 88 668 617 140
8.98 26.00 92 98 98 92 683 632 140
9.33 26.00 96 102 102 96 670 621 140
9.80 26.00 100 106 106 100 672 623 140
9.95 25.99 104 110 110 104 677 628 140
10.11 26.00 108 114 114 108 698 649 140
10.70 26.00 112 118 118 112 677 626 140
11.10 26.00 116 122 122 116 681 630 140
11.54 26.00 120 126 126 120 683 636 140
11.78 26.00 124 130 130 124 683 634 140
12.08 26.00 128 
```

detailed log here...
[log.txt](https://github.com/OFS/ofs-platform-afu-bbb/files/15091968/log.txt)

**Comment by umairsiddiqui-digitek** [comment]
I build AXI4 version with:

```
afu_synth_setup -s hw/rtl/test_axi7_burst3.txt afu_dev_axi
cd afu_dev_axi/
$OPAE_PLATFORM_ROOT/bin/afu_synth
```

however, facing same issue with AXI4 (`test_axi7_burst3.txt`) in latency mode:

```
./host_chan_params --latency
```
[log_axi2.txt](https://github.com/OFS/ofs-platform-afu-bbb/files/15094660/log_axi2.txt)

**Comment by michael-adler** [comment]
Thank you. I reproduced it. The bug is in the SW, not the HW. The HW has been constrained so the burst size field limits the maximum size to 4. If you run host_chan_params without the --latency switch you will see that it behaves properly. The --latency variant is ignoring the constraint. I will fix it, but for now just don't use --latency with that variant.

Note that the majority of the host_chan_params tests other than 0 (normal) and 1 (user clock) are aimed at testing PIM configurations. They are all tested with the normal host_chan_params but not with --latency, which is used only for performance characterization.

**Comment by michael-adler** [comment]
Fixed
